import type { CodeReview, ReviewFinding } from './reviewSchema';

const commentMarker = '<!-- ai-code-review-bot -->';

const severityIcons = {
  critical: '🚨',
  high: '🔴',
  medium: '🟠',
  low: '🔵',
} as const;

function escapeMarkdown(value: string): string {
  return value.replaceAll('\\', '\\\\').replaceAll('`', '\\`');
}

function formatFinding(finding: ReviewFinding, index: number): string {
  const icon = severityIcons[finding.severity];
  const confidence = Math.round(finding.confidence * 100);
  const line = finding.line === null ? '' : `:${finding.line}`;

  return `
### ${index + 1}. ${icon} ${finding.severity.toUpperCase()} — ${escapeMarkdown(finding.title)}

- **Category:** ${finding.category}
- **Language:** ${finding.language}
- **Location:** \`${escapeMarkdown(finding.file)}${line}\`
- **Confidence:** ${confidence}%

**Why this matters**

${escapeMarkdown(finding.explanation)}

**Suggested fix**

${escapeMarkdown(finding.suggestedFix)}
`.trim();
}

export function formatReviewComment(
  review: CodeReview,
  requestId: string,
): string {
  const riskIcon = severityIcons[review.riskLevel];

  const findings =
    review.findings.length > 0
      ? review.findings
          .map((finding, index) => formatFinding(finding, index))
          .join('\n\n---\n\n')
      : '✅ No meaningful issues were found in the changed code.';

  const positives =
    review.positives.length > 0
      ? review.positives
          .map((positive) => `- ${escapeMarkdown(positive)}`)
          .join('\n')
      : '- No specific positive observations were returned.';

  return `
${commentMarker}

## 🤖 AI Code Review

**Overall risk:** ${riskIcon} ${review.riskLevel.toUpperCase()}

${escapeMarkdown(review.summary)}

## Findings

${findings}

## What was done well

${positives}

---

<sub>Generated by GitHub Copilot using custom engineering standards. Request ID: \`${requestId}\`. AI feedback must be verified by a human reviewer.</sub>
`.trim();
}
